### ISSUE TITLE
XFCE Update Manager "Download" window is unstyled

### ISSUE THREAD

**Issue by cdcrchrisparker** [EliverLara/Andromeda-gtk#3]
Update manager proper has the proper colors, but the window that appears when downloading updates is the default XFCE style.  See attached image.
![XFCE_Download_Manager](https://github.com/EliverLara/Andromeda-gtk/assets/97982332/75fc1c06-d8c4-474f-91fa-605f9aeaa07f)

P.S. I love the theme!  Happy to try and help with this issue - perhaps you have some clue as to where to look?

**Comment by EliverLara** [comment]
Hi, if the application requires `sudo` permissions the theme must be installed under` /usr/share/themes/`

**Comment by cdcrchrisparker** [comment]
Oh sheesh, that makes perfect sense! You are spot on, I have it in ~/.themes to try it out. Funny, I previously tried to create my own theme, and it had similar issues - among MANY others. Designing a theme is surprisingly difficult to get correct.

I'm glad I found your theme. Thanks x 1,000,000.
